name: dart_web_sockets
description: A simple app to demonstrate the use of Web Sockets in the Dart
    programming language
dependencies:
    browser: any
    http_server: ">=0.9.0 <0.10.0"
    http: ">=0.9.0 <0.10.0"
    route: ">=0.4.0 <0.5.0"
environment:
    sdk: ">=1.7.2 <2.0.0"

