name:  sortable_list
description: A Dart/Polymer application that allows you to sort a list

dependencies:
    polymer: ">=0.12.0 <0.13.0"
transformers:
- polymer:
    entry_points:
    - web/index.html
dev_dependencies:
    unittest: ">=0.9.0 <0.10.0"

